### ISSUE TITLE
Issues with display being interrupted if Japanese is included

### ISSUE THREAD

**Issue by Remiaaaaa** [Exle/AIMP-Discord-Presence#2]
Issues that can be displayed when Japanese is included in artist name, album name, song title etc of song
![image](https://user-images.githubusercontent.com/36363244/39085534-d41a961e-45be-11e8-8e7b-f3730ffc2ab5.png)
![image](https://user-images.githubusercontent.com/36363244/39085537-ec5777c4-45be-11e8-8fe8-2699b827bc06.png)

**Comment by Exle** [comment]
Fixed in [v1.0.0.5](http://www.aimp.ru/forum/index.php?topic=59461.msg369172#msg369172).
You can find latest release [here](https://github.com/Exle/AIMP-Discord-Presence/releases/latest) or [attachment in first post](http://www.aimp.ru/forum/index.php?topic=59461.msg368976#msg_368973)
![image](https://user-images.githubusercontent.com/25784007/39097248-6ed4d28e-4662-11e8-9069-47629fa5c621.png)
